# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94eba0542c1b478a8c426d17ded466165eb1d8a09a79a1e2255313f9bd81368dc4e15ef395995e9529d4b3558bff02d8039e7b63dd78d998ef01e499b63a4872

test:
  secret_key_base: 0233c20a8a5c2e074f3552beaccb3985b534cf2fe055d24d05b60ed0a63bcd5f36f7677ad1af10e0b057d9c092a6344f60f4658ab43e3402f94736ce4dd000bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
